services:
  mysql:
    image: mysql:9.1.0
    ports:
      - "3360:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mientreno
  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  mailpit:
    image: axllent/mailpit:v1.21.8
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
  rabbitmq_data: