files:
  - source: /Compartido/Recursos/AppStrings.resx
    translation: /Compartido/Recursos/AppStrings.%two_letters_code%.resx
  - source: /Server/EmailTemplates/**/default.md
    translation: /Server/EmailTemplates/**/%two_letters_code%.md