//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mientreno.Compartido.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mientreno.Compartido.Recursos.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar.
        /// </summary>
        public static string Action_Contact {
            get {
                return ResourceManager.GetString("Action_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva categoría.
        /// </summary>
        public static string Action_CreateCategory {
            get {
                return ResourceManager.GetString("Action_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar MFA.
        /// </summary>
        public static string Action_DisableMFA {
            get {
                return ResourceManager.GetString("Action_DisableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar MFA.
        /// </summary>
        public static string Action_EnableMFA {
            get {
                return ResourceManager.GetString("Action_EnableMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Action_Exit {
            get {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar códigos.
        /// </summary>
        public static string Action_GenerateCodes {
            get {
                return ResourceManager.GetString("Action_GenerateCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar.
        /// </summary>
        public static string Action_Invite {
            get {
                return ResourceManager.GetString("Action_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string Action_Logout {
            get {
                return ResourceManager.GetString("Action_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar.
        /// </summary>
        public static string Action_Manage {
            get {
                return ResourceManager.GetString("Action_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar mi cuenta.
        /// </summary>
        public static string Action_ManageAccount {
            get {
                return ResourceManager.GetString("Action_ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string Action_See {
            get {
                return ResourceManager.GetString("Action_See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Action_Send {
            get {
                return ResourceManager.GetString("Action_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu cuenta ha sido confirmada. Ya puedes iniciar sesión y empezar a utilizar MiEntreno..
        /// </summary>
        public static string Alert_AccountConfirmed_Text {
            get {
                return ResourceManager.GetString("Alert_AccountConfirmed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta confirmada.
        /// </summary>
        public static string Alert_AccountConfirmed_Title {
            get {
                return ResourceManager.GetString("Alert_AccountConfirmed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que has excedido tu cuota de alumnos. Si quieres invitar a más, considera cambiarte a un plan superior..
        /// </summary>
        public static string Alert_CannotInviteQuotaExceeded_Text {
            get {
                return ResourceManager.GetString("Alert_CannotInviteQuotaExceeded_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden invitar más alumnos.
        /// </summary>
        public static string Alert_CannotInviteQuotaExceeded_Title {
            get {
                return ResourceManager.GetString("Alert_CannotInviteQuotaExceeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus datos de contacto fueron cubiertos automáticamente porque tienes la sesión iniciada. Si tu plan incluye soporte prioritario, este se tendrá en cuenta..
        /// </summary>
        public static string Alert_ContactPreFilled_Text {
            get {
                return ResourceManager.GetString("Alert_ContactPreFilled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes la sesión iniciada.
        /// </summary>
        public static string Alert_ContactPreFilled_Title {
            get {
                return ResourceManager.GetString("Alert_ContactPreFilled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has contactado exitosamente con el equipo de MiEntreno. Te contestaremos lo antes posible..
        /// </summary>
        public static string Alert_ContactSent_Text {
            get {
                return ResourceManager.GetString("Alert_ContactSent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu mensaje se ha enviado.
        /// </summary>
        public static string Alert_ContactSent_Title {
            get {
                return ResourceManager.GetString("Alert_ContactSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La invitación no es válida, porque no existe, ha caducado, o tu entrenador no puede invitar más alumnos en estos momentos..
        /// </summary>
        public static string Alert_InviteInvalid_Text {
            get {
                return ResourceManager.GetString("Alert_InviteInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitación inválida.
        /// </summary>
        public static string Alert_InviteInvalid_Title {
            get {
                return ResourceManager.GetString("Alert_InviteInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invita a tus alumnos a unirse a tí generando una invitación en la parte superior derecha..
        /// </summary>
        public static string Alert_NoAlumnos_Text {
            get {
                return ResourceManager.GetString("Alert_NoAlumnos_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes alumnos.
        /// </summary>
        public static string Alert_NoAlumnos_Title {
            get {
                return ResourceManager.GetString("Alert_NoAlumnos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si hay un usuario con la dirección de correo electrónico que nos facilitaste, recibirás un enlace con el que podrás restablecer tu contraseña..
        /// </summary>
        public static string Alert_PasswordRecoverySent_Text {
            get {
                return ResourceManager.GetString("Alert_PasswordRecoverySent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlace de reinicio enviado.
        /// </summary>
        public static string Alert_PasswordRecoverySent_Title {
            get {
                return ResourceManager.GetString("Alert_PasswordRecoverySent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, almacena estos códigos en un lugar seguro. Una vez salgas de esta página, no podrás volver a verlos..
        /// </summary>
        public static string Alert_RecoveryCodesGenerated_Text {
            get {
                return ResourceManager.GetString("Alert_RecoveryCodesGenerated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos generados.
        /// </summary>
        public static string Alert_RecoveryCodesGenerated_Title {
            get {
                return ResourceManager.GetString("Alert_RecoveryCodesGenerated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para confirmar tu cuenta, te hemos enviado un correo electrónico. Por favor, revisa tu bandeja de entrada..
        /// </summary>
        public static string Alert_RegistrationDoneEmailSent_Text {
            get {
                return ResourceManager.GetString("Alert_RegistrationDoneEmailSent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te estás registrando como Alumno de.
        /// </summary>
        public static string Alert_SignUpInvite_Text {
            get {
                return ResourceManager.GetString("Alert_SignUpInvite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te ha invitado a entrenar.
        /// </summary>
        public static string Alert_SignUpInvite_Title {
            get {
                return ResourceManager.GetString("Alert_SignUpInvite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error.
        /// </summary>
        public static string Alert_UnexpectedError_Title {
            get {
                return ResourceManager.GetString("Alert_UnexpectedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores de validación.
        /// </summary>
        public static string Alert_ValidationErrors_Title {
            get {
                return ResourceManager.GetString("Alert_ValidationErrors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes cuenta? Inicia sesión..
        /// </summary>
        public static string alreadyHaveAccountLogin {
            get {
                return ResourceManager.GetString("alreadyHaveAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnos.
        /// </summary>
        public static string alumnos {
            get {
                return ResourceManager.GetString("alumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta funcionalidad estará disponible próximamente..
        /// </summary>
        public static string availableSoon {
            get {
                return ResourceManager.GetString("availableSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacta con nosotros.
        /// </summary>
        public static string CallToAction_Contact {
            get {
                return ResourceManager.GetString("CallToAction_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o inicia sesión.
        /// </summary>
        public static string CallToAction_OrLogIn {
            get {
                return ResourceManager.GetString("CallToAction_OrLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Regístrate ya!.
        /// </summary>
        public static string CallToAction_SignUpNow {
            get {
                return ResourceManager.GetString("CallToAction_SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuestionario.
        /// </summary>
        public static string cuestionario {
            get {
                return ResourceManager.GetString("cuestionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuestionarios.
        /// </summary>
        public static string cuestionarios {
            get {
                return ResourceManager.GetString("cuestionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi tablero.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes registrados {0} alumnos de los {1} que permite tu suscripción..
        /// </summary>
        public static string dashboard_AlumnosOutOf {
            get {
                return ResourceManager.GetString("dashboard_AlumnosOutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ponte en contacto con nosotros.
        /// </summary>
        public static string dashboard_GetInTouch {
            get {
                return ResourceManager.GetString("dashboard_GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitación creada.
        /// </summary>
        public static string dashboard_InviteCreated {
            get {
                return ResourceManager.GetString("dashboard_InviteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha creado ningún cuestionario (todavía)..
        /// </summary>
        public static string dashboard_NoCuestionariosCreated {
            get {
                return ResourceManager.GetString("dashboard_NoCuestionariosCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha creado ningún plan de entrenamiento (todavía)..
        /// </summary>
        public static string dashboard_NoPlansCreated {
            get {
                return ResourceManager.GetString("dashboard_NoPlansCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes una suscripción activa..
        /// </summary>
        public static string dashboard_NotSubscribedToPlan {
            get {
                return ResourceManager.GetString("dashboard_NotSubscribedToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tuvieras algún problema con tu suscripción, por favor.
        /// </summary>
        public static string dashboard_ProblemWithStripe {
            get {
                return ResourceManager.GetString("dashboard_ProblemWithStripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparte el siguiente enlace con tu(s) alumno(s):.
        /// </summary>
        public static string dashboard_ShareInviteLink {
            get {
                return ResourceManager.GetString("dashboard_ShareInviteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panel de control de cliente de Stripe.
        /// </summary>
        public static string dashboard_StripeClientPanel {
            get {
                return ResourceManager.GetString("dashboard_StripeClientPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes una suscripción activa al plan .
        /// </summary>
        public static string dashboard_SubscribedToPlan {
            get {
                return ResourceManager.GetString("dashboard_SubscribedToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu suscripción será renovada automáticamente el .
        /// </summary>
        public static string dashboard_SubscriptionWillBeRenewedAt {
            get {
                return ResourceManager.GetString("dashboard_SubscriptionWillBeRenewedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu suscrpción no será renovada, y finalizará el .
        /// </summary>
        public static string dashboard_SubscriptionWillEndAt {
            get {
                return ResourceManager.GetString("dashboard_SubscriptionWillEndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizamos Stripe para procesar los pagos de forma segura. Puedes administrar tu suscripción en tu.
        /// </summary>
        public static string dashboard_WeUseStripe {
            get {
                return ResourceManager.GetString("dashboard_WeUseStripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificultad.
        /// </summary>
        public static string dificultad {
            get {
                return ResourceManager.GetString("dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo ejercicio.
        /// </summary>
        public static string Doing_CrearEjercicio {
            get {
                return ResourceManager.GetString("Doing_CrearEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editando ejercicio.
        /// </summary>
        public static string Doing_EditarEjercicio {
            get {
                return ResourceManager.GetString("Doing_EditarEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperación de contraseña.
        /// </summary>
        public static string Doing_PasswordRecovery {
            get {
                return ResourceManager.GetString("Doing_PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estableciendo tu contraseña.
        /// </summary>
        public static string Doing_SetPassword {
            get {
                return ResourceManager.GetString("Doing_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando que eres tú.
        /// </summary>
        public static string Doing_VerifyIdentity {
            get {
                return ResourceManager.GetString("Doing_VerifyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejercicios.
        /// </summary>
        public static string ejercicios {
            get {
                return ResourceManager.GetString("ejercicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrectos.
        /// </summary>
        public static string Error_IncorrectCredentials {
            get {
                return ResourceManager.GetString("Error_IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de autenticador inválido.
        /// </summary>
        public static string Error_IncorrectMfaCode {
            get {
                return ResourceManager.GetString("Error_IncorrectMfaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de restablecimiento incorrecto.
        /// </summary>
        public static string Error_InvalidResetToken {
            get {
                return ResourceManager.GetString("Error_InvalidResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a mi tablero.
        /// </summary>
        public static string goToDashboard {
            get {
                return ResourceManager.GetString("goToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string Input_ConfirmPassword {
            get {
                return ResourceManager.GetString("Input_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Input_Descripcion {
            get {
                return ResourceManager.GetString("Input_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string Input_Email {
            get {
                return ResourceManager.GetString("Input_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Input_Message {
            get {
                return ResourceManager.GetString("Input_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código del autenticador.
        /// </summary>
        public static string Input_MfaCode {
            get {
                return ResourceManager.GetString("Input_MfaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Input_Name {
            get {
                return ResourceManager.GetString("Input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Input_Password {
            get {
                return ResourceManager.GetString("Input_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar plan (no se podrá modificar más tarde).
        /// </summary>
        public static string Input_PublishPlanUnableEditLater {
            get {
                return ResourceManager.GetString("Input_PublishPlanUnableEditLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar este dispositivo.
        /// </summary>
        public static string Input_RememberDevice {
            get {
                return ResourceManager.GetString("Input_RememberDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantener sesión iniciada.
        /// </summary>
        public static string Input_RememberMe {
            get {
                return ResourceManager.GetString("Input_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido(s).
        /// </summary>
        public static string Input_Surname {
            get {
                return ResourceManager.GetString("Input_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL de vídeo demostrativo.
        /// </summary>
        public static string Input_VideoUrl {
            get {
                return ResourceManager.GetString("Input_VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He leído y acepto.
        /// </summary>
        public static string iveReadAndAccept {
            get {
                return ResourceManager.GetString("iveReadAndAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más detalles.
        /// </summary>
        public static string masDetalles {
            get {
                return ResourceManager.GetString("masDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Nuevo por aquí? Regístrate..
        /// </summary>
        public static string newHereRegister {
            get {
                return ResourceManager.GetString("newHereRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna categoría creada.
        /// </summary>
        public static string noHayCategorias {
            get {
                return ResourceManager.GetString("noHayCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrador.
        /// </summary>
        public static string Noun_EstadoRutina_Borrador {
            get {
                return ResourceManager.GetString("Noun_EstadoRutina_Borrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En curso.
        /// </summary>
        public static string Noun_EstadoRutina_EnCurso {
            get {
                return ResourceManager.GetString("Noun_EstadoRutina_EnCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluado.
        /// </summary>
        public static string Noun_EstadoRutina_Evaluada {
            get {
                return ResourceManager.GetString("Noun_EstadoRutina_Evaluada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado.
        /// </summary>
        public static string Noun_EstadoRutina_Finalizada {
            get {
                return ResourceManager.GetString("Noun_EstadoRutina_Finalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicado.
        /// </summary>
        public static string Noun_EstadoRutina_Publicada {
            get {
                return ResourceManager.GetString("Noun_EstadoRutina_Publicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitaciones.
        /// </summary>
        public static string Noun_Invite_Plural {
            get {
                return ResourceManager.GetString("Noun_Invite_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin nombre.
        /// </summary>
        public static string Noun_JornadaEntrenamiento_NoName {
            get {
                return ResourceManager.GetString("Noun_JornadaEntrenamiento_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Noun_Language {
            get {
                return ResourceManager.GetString("Noun_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euskera.
        /// </summary>
        public static string Noun_Language_Basque {
            get {
                return ResourceManager.GetString("Noun_Language_Basque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalán.
        /// </summary>
        public static string Noun_Language_Catalan {
            get {
                return ResourceManager.GetString("Noun_Language_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string Noun_Language_English {
            get {
                return ResourceManager.GetString("Noun_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallego.
        /// </summary>
        public static string Noun_Language_Galician {
            get {
                return ResourceManager.GetString("Noun_Language_Galician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Noun_Language_Spanish {
            get {
                return ResourceManager.GetString("Noun_Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan.
        /// </summary>
        public static string Noun_Plan_Singular {
            get {
                return ResourceManager.GetString("Noun_Plan_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de entrenamiento.
        /// </summary>
        public static string Noun_Rutina_Plural {
            get {
                return ResourceManager.GetString("Noun_Rutina_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Page_Contact {
            get {
                return ResourceManager.GetString("Page_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de recuperación.
        /// </summary>
        public static string Page_GenerateCodes {
            get {
                return ResourceManager.GetString("Page_GenerateCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Page_Landing {
            get {
                return ResourceManager.GetString("Page_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        public static string Page_Login {
            get {
                return ResourceManager.GetString("Page_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar MFA.
        /// </summary>
        public static string Page_MfaDisable {
            get {
                return ResourceManager.GetString("Page_MfaDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar MFA.
        /// </summary>
        public static string Page_MfaSetup {
            get {
                return ResourceManager.GetString("Page_MfaSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        public static string Page_MyAccount {
            get {
                return ResourceManager.GetString("Page_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes y tarifas.
        /// </summary>
        public static string Page_Pricing {
            get {
                return ResourceManager.GetString("Page_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Page_Register {
            get {
                return ResourceManager.GetString("Page_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información legal.
        /// </summary>
        public static string Page_Terms {
            get {
                return ResourceManager.GetString("Page_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los códigos de recuperación son necesarios si pierdes tu autenticador MFA. Si ya generaste códigos previamente, generarlos de nuevo invalidará los ya existentes..
        /// </summary>
        public static string Text_Accounts_Accounts_RecoveryCodesAreFor {
            get {
                return ResourceManager.GetString("Text_Accounts_Accounts_RecoveryCodesAreFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar autenticación de dos factores.
        /// </summary>
        public static string Text_Accounts_DisableMfa {
            get {
                return ResourceManager.GetString("Text_Accounts_DisableMfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar autenticación de dos factores.
        /// </summary>
        public static string Text_Accounts_EnableMfa {
            get {
                return ResourceManager.GetString("Text_Accounts_EnableMfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña para desactivar la autenticación de doble factor..
        /// </summary>
        public static string Text_Accounts_EnterPasswordToDisableMfa {
            get {
                return ResourceManager.GetString("Text_Accounts_EnterPasswordToDisableMfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña para regenerar tus códigos de recuperación..
        /// </summary>
        public static string Text_Accounts_EnterPasswordToRegenerateCodes {
            get {
                return ResourceManager.GetString("Text_Accounts_EnterPasswordToRegenerateCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerar códigos de recuperación.
        /// </summary>
        public static string Text_Accounts_GenerateRecoveryCodes {
            get {
                return ResourceManager.GetString("Text_Accounts_GenerateRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si perdiste tu autenticador, puedes utilizar uno de tus códigos de recuperación. Si no tienes códigos de recuperación, &lt;a href=&quot;/Contact&quot; class=&quot;link link-primary link-bold&quot;&gt;ponte en contacto con nosotros&lt;/a&gt;..
        /// </summary>
        public static string Text_Accounts_IfYouLostMfaCode {
            get {
                return ResourceManager.GetString("Text_Accounts_IfYouLostMfaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios para tu entrenador.
        /// </summary>
        public static string Text_Alumnos_FeedbackComments {
            get {
                return ResourceManager.GetString("Text_Alumnos_FeedbackComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuación general.
        /// </summary>
        public static string Text_Alumnos_FeedbackScore {
            get {
                return ResourceManager.GetString("Text_Alumnos_FeedbackScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes entrenamientos programados. Si crees que se trata de un error, ponte en contacto con tu entrenador..
        /// </summary>
        public static string Text_Alumnos_NoJornadasScheduled {
            get {
                return ResourceManager.GetString("Text_Alumnos_NoJornadasScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizado hace.
        /// </summary>
        public static string Text_Alumnos_Plan_DoneAt {
            get {
                return ResourceManager.GetString("Text_Alumnos_Plan_DoneAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluado el.
        /// </summary>
        public static string Text_Alumnos_Plan_ReviewedAt {
            get {
                return ResourceManager.GetString("Text_Alumnos_Plan_ReviewedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzado hace.
        /// </summary>
        public static string Text_Alumnos_Plan_StartedAt {
            get {
                return ResourceManager.GetString("Text_Alumnos_Plan_StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamientos programados.
        /// </summary>
        public static string Text_Alumnos_ScheduledJornadas {
            get {
                return ResourceManager.GetString("Text_Alumnos_ScheduledJornadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes contactar con nosotros a través de nuestro correo electrónico: &lt;a href=&quot;mailto:hola@mientreno.app&quot; class=&quot;link link-primary link-bold&quot;&gt;hola@mientreno.app&lt;/a&gt;. Alternativamente, puedes contactar con nosotros a través del siguiente formulario de contacto (respondemos en 1-2 días):.
        /// </summary>
        public static string Text_Contact_Methods {
            get {
                return ResourceManager.GetString("Text_Contact_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos introducidos en este formulario serán enviados a nuestro correo electrónico y no serán almacenados en ninguna base de datos. &lt;strong&gt;	No comparta contraseñas o información sensible a través de este formulario.&lt;/strong&gt;.
        /// </summary>
        public static string Text_Contact_Privacy {
            get {
                return ResourceManager.GetString("Text_Contact_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoración del alumno.
        /// </summary>
        public static string Text_Dashboard_AlumnoFeedback {
            get {
                return ResourceManager.GetString("Text_Dashboard_AlumnoFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi cuenta.
        /// </summary>
        public static string Text_Dashboard_MyAccount_Title {
            get {
                return ResourceManager.GetString("Text_Dashboard_MyAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis alumnos.
        /// </summary>
        public static string Text_Dashboard_MyAlumnos_Title {
            get {
                return ResourceManager.GetString("Text_Dashboard_MyAlumnos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi suscripción.
        /// </summary>
        public static string Text_Dashboard_MySuscripcion_Title {
            get {
                return ResourceManager.GetString("Text_Dashboard_MySuscripcion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu suscripción ha sido confirmada correctamente. A continuación, puedes ir a tu tablero y empezar a trabajar con MiEntreno..
        /// </summary>
        public static string Text_Dashboard_SubscriptionConfirmed_Text {
            get {
                return ResourceManager.GetString("Text_Dashboard_SubscriptionConfirmed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu suscripción fue confirmada.
        /// </summary>
        public static string Text_Dashboard_SubscriptionConfirmed_Title {
            get {
                return ResourceManager.GetString("Text_Dashboard_SubscriptionConfirmed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haznos llegar tus consultas, y las resolveremos lo antes posible..
        /// </summary>
        public static string Text_LandingPage_ContactUsQuestions {
            get {
                return ResourceManager.GetString("Text_LandingPage_ContactUsQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiona los entrenamientos de tus clientes: qué ejercicios realizar, cuántas series y repeticiones. Añade un vídeo para demostrar la realización del ejercicio..
        /// </summary>
        public static string Text_LandingPage_Feature1_Text {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiona entrenamientos.
        /// </summary>
        public static string Text_LandingPage_Feature1_Title {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiEntreno funciona desde cualquier dispositivo con conexión a internet. Permite que tu cliente revise la rutina asignada o los detalles de un ejercicio concreto desde cualquier lugar, visualizándose de una forma amigable y adaptada al dispositivo..
        /// </summary>
        public static string Text_LandingPage_Feature2_Text {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde cualquier lugar, en cualquier momento.
        /// </summary>
        public static string Text_LandingPage_Feature2_Title {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta el historial de entrenamientos para ver la evolución del cliente. Recibe feedback inmediato tras la realización de cada rutina; para poder adaptarte mejor a sus capacidades y sus necesidades..
        /// </summary>
        public static string Text_LandingPage_Feature3_Text {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de entrenamientos.
        /// </summary>
        public static string Text_LandingPage_Feature3_Title {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mientreno está en constante desarrollo. Con el tiempo, irás obteniendo acceso a nuevas funcionalidades y mejoras..
        /// </summary>
        public static string Text_LandingPage_Feature4_Text {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siempre a mejor.
        /// </summary>
        public static string Text_LandingPage_Feature4_Title {
            get {
                return ResourceManager.GetString("Text_LandingPage_Feature4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mientreno te permite gestionar los entrenamientos físicos de tus clientes de forma sencilla y eficaz..
        /// </summary>
        public static string Text_LandingPage_Text {
            get {
                return ResourceManager.GetString("Text_LandingPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una nueva forma de entrenar.
        /// </summary>
        public static string Text_LandingPage_Title {
            get {
                return ResourceManager.GetString("Text_LandingPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres saber más? ¿Tienes alguna duda?.
        /// </summary>
        public static string Text_LandingPage_WannaKnowMore {
            get {
                return ResourceManager.GetString("Text_LandingPage_WannaKnowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por cuestiones fiscales, si eres autónomo o empresa, debes &lt;a href=&quot;/Contact&quot;&gt;ponerte en contacto con nosotros&lt;/a&gt; previamente..
        /// </summary>
        public static string Text_Pricing_AvisoAutonomos {
            get {
                return ResourceManager.GetString("Text_Pricing_AvisoAutonomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con las nuevas suscripciones se incluye un periodo de prueba de 14 días, tras los cuales se renovará automáticamente la suscripción, a no ser que se cancele antes de que finalice el periodo de prueba..
        /// </summary>
        public static string Text_Pricing_Free14DayTrial {
            get {
                return ResourceManager.GetString("Text_Pricing_Free14DayTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si eres un alumno de un entrenador, no necesitas una suscripción, y MiEntreno será totalmente gratuito para ti..
        /// </summary>
        public static string Text_Pricing_FreeForAlumnos {
            get {
                return ResourceManager.GetString("Text_Pricing_FreeForAlumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cada plan, se puede elegir entre una suscripción mensual o anual. La suscripción anual tiene un descuento equivalente a dos meses gratis. Si se elige la suscripción anual, se cobrará el importe total de la suscripción al inicio del periodo de suscripción..
        /// </summary>
        public static string Text_Pricing_MonthlyAndAnnuallyAvailable {
            get {
                return ResourceManager.GetString("Text_Pricing_MonthlyAndAnnuallyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso prioritario a soporte técnico.
        /// </summary>
        public static string Text_Pricing_PrioritySupport {
            get {
                return ResourceManager.GetString("Text_Pricing_PrioritySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para gestionar entrenamientos utilizando MiEntreno es necesaria una suscripción. Contamos con varios planes, para que puedas elegir el que mejor se adapte a tus necesidades. Para suscribirte, debes registrarte en MiEntreno, y una vez inicies sesión por primera vez, podrás elegir el plan que prefieras..
        /// </summary>
        public static string Text_Pricing_SubscriptionNeeded {
            get {
                return ResourceManager.GetString("Text_Pricing_SubscriptionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrena hasta {0} personas.
        /// </summary>
        public static string Text_Pricing_TrainUpToPeople {
            get {
                return ResourceManager.GetString("Text_Pricing_TrainUpToPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to los términos y condiciones.
        /// </summary>
        public static string theTermsAndConditions {
            get {
                return ResourceManager.GetString("theTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir tu correo electrónico.
        /// </summary>
        public static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir tu nombre.
        /// </summary>
        public static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string Validation_Password_DontMatch {
            get {
                return ResourceManager.GetString("Validation_Password_DontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir la contraseña.
        /// </summary>
        public static string Validation_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial.
        /// </summary>
        public static string Validation_Password_Weak {
            get {
                return ResourceManager.GetString("Validation_Password_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes confirmar la contraseña.
        /// </summary>
        public static string Validation_PasswordConfirmation_Required {
            get {
                return ResourceManager.GetString("Validation_PasswordConfirmation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes introducir tus apellidos.
        /// </summary>
        public static string Validation_Surname_Required {
            get {
                return ResourceManager.GetString("Validation_Surname_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes aceptar los términos y condiciones.
        /// </summary>
        public static string Validation_Tos_Unchecked {
            get {
                return ResourceManager.GetString("Validation_Tos_Unchecked", resourceCulture);
            }
        }
    }
}
