//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mientreno.Compartido.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mientreno.Compartido.Recursos.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes cuenta? Inicia sesión..
        /// </summary>
        public static string alreadyHaveAccountLogin {
            get {
                return ResourceManager.GetString("alreadyHaveAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string doLogin {
            get {
                return ResourceManager.GetString("doLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string doRegister {
            get {
                return ResourceManager.GetString("doRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes introducir usuario y contraseña.
        /// </summary>
        public static string enterUsernameOrPassword {
            get {
                return ResourceManager.GetString("enterUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string errorCredencialesInvalidas {
            get {
                return ResourceManager.GetString("errorCredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error inesperado. Inténtalo de nuevo más tarde..
        /// </summary>
        public static string errorUnexpected {
            get {
                return ResourceManager.GetString("errorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión para continuar.
        /// </summary>
        public static string loginToContinue {
            get {
                return ResourceManager.GetString("loginToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nuevo por aquí? Regístrate..
        /// </summary>
        public static string newHereRegister {
            get {
                return ResourceManager.GetString("newHereRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string passwordsDoNotMatch {
            get {
                return ResourceManager.GetString("passwordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es demasiado débil. Debe contener al menos 8 caracteres, con mayúsculas y minúsculas, números y/o símbolos..
        /// </summary>
        public static string passwordTooWeak {
            get {
                return ResourceManager.GetString("passwordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o dirección de correo ya están registrados..
        /// </summary>
        public static string usernameOrEmailAlreadyInUse {
            get {
                return ResourceManager.GetString("usernameOrEmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al registrarte, estás aceptando nuestros términos de uso y nuestra política de privacidad..
        /// </summary>
        public static string youAcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("youAcceptTermsAndConditions", resourceCulture);
            }
        }
    }
}
