// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mientreno.Server.Data;

#nullable disable

namespace Mientreno.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20250119131039_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Cuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("AlturaCm")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Edad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFormalizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("FrecuenciaCardiacaReposo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<float>("MasaKilogramos")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Dificultad")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.EjercicioProgramado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<string>("JornadaId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Minutos")
                        .HasColumnType("int");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("JornadaId");

                    b.ToTable("EjercicioProgramado");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Invitacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntrenadorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("MaximoUsos")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Usos")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.JornadaEntrenamiento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClienteAsignadoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEvalucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFinRealizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioRealizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Valoracion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ClienteAsignadoId");

                    b.ToTable("JornadaEntrenamiento");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Usuario", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("UltimosTosAceptados")
                        .HasColumnType("int unsigned");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Alumno", b =>
                {
                    b.HasBaseType("Mientreno.Server.Data.Models.Usuario");

                    b.Property<string>("EntrenadorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasIndex("EntrenadorId");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Entrenador", b =>
                {
                    b.HasBaseType("Mientreno.Server.Data.Models.Usuario");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Categoria", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Entrenador", "Owner")
                        .WithMany("Categorias")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Cuestionario", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Alumno", "Alumno")
                        .WithMany("Cuestionarios")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mientreno.Server.Data.Models.Habitos", "Habitos", b1 =>
                        {
                            b1.Property<Guid>("CuestionarioId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Bebedor")
                                .HasColumnType("int");

                            b1.Property<int>("Deporte")
                                .HasColumnType("int");

                            b1.Property<int>("Fumador")
                                .HasColumnType("int");

                            b1.Property<string>("OtrasDrogas")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Profesion")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Sueño")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CuestionarioId");

                            b1.ToTable("Cuestionarios");

                            b1.WithOwner()
                                .HasForeignKey("CuestionarioId");
                        });

                    b.OwnsOne("Mientreno.Server.Data.Models.Perimetros", "Perimetros", b1 =>
                        {
                            b1.Property<Guid>("CuestionarioId")
                                .HasColumnType("char(36)");

                            b1.Property<byte>("AbdominalOmbligo")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("AbdominalXifoides")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("Cadera")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("Cintura")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("CuadricepsMaximo")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("CuadricepsMinimo")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("Gastrocnemio")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("PectoralExpiracion")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("PectoralInspiracion")
                                .HasColumnType("tinyint unsigned");

                            b1.HasKey("CuestionarioId");

                            b1.ToTable("Cuestionarios");

                            b1.WithOwner()
                                .HasForeignKey("CuestionarioId");
                        });

                    b.Navigation("Alumno");

                    b.Navigation("Habitos")
                        .IsRequired();

                    b.Navigation("Perimetros")
                        .IsRequired();
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Ejercicio", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Categoria", "Categoria")
                        .WithMany("Ejercicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mientreno.Server.Data.Models.Entrenador", "Owner")
                        .WithMany("Ejercicios")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.EjercicioProgramado", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mientreno.Server.Data.Models.JornadaEntrenamiento", "Jornada")
                        .WithMany("Ejercicios")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Invitacion", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Entrenador", "Entrenador")
                        .WithMany("Invitaciones")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.JornadaEntrenamiento", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Alumno", "ClienteAsignado")
                        .WithMany("JornadasEntrenamientos")
                        .HasForeignKey("ClienteAsignadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteAsignado");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Alumno", b =>
                {
                    b.HasOne("Mientreno.Server.Data.Models.Entrenador", "Entrenador")
                        .WithMany("Alumnos")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Categoria", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.JornadaEntrenamiento", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Alumno", b =>
                {
                    b.Navigation("Cuestionarios");

                    b.Navigation("JornadasEntrenamientos");
                });

            modelBuilder.Entity("Mientreno.Server.Data.Models.Entrenador", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Categorias");

                    b.Navigation("Ejercicios");

                    b.Navigation("Invitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
